# Generated by Django 4.0.3 on 2022-05-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ils', '0002_alter_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card_number', models.CharField(max_length=9, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('membership_end_date', models.DateField(default=ils.models.Reader.get_one_year_from_today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ils.reader')),
            ],
        ),
    ]