# Generated by Django 4.0.3 on 2022-05-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ils', '0003_reader_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_available_at', models.DateTimeField(blank=True, null=True)),
                ('termination_type', models.CharField(blank=True, choices=[('Completed', 'Reservation completed'), ('Cancelled', 'Reservation cancelled'), ('Forfeited', 'Reservation forfeited')], max_length=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ils.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ils.reader')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
