# Generated by Django 4.0.3 on 2022-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ils', '0005_bookloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
