# Generated by Django 4.0.3 on 2022-06-12 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ils', '0008_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
