# Generated by Django 4.0.3 on 2022-06-12 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ils', '0011_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(default=2000, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
    ]
